# vi: set ft=ruby :#

raise 'Vagrant plugin "vagrant-berkshelf" is required!' unless Vagrant.has_plugin? 'vagrant-berkshelf'

Vagrant.configure(2) do |config|
    config.vm.box = 'bento/centos-7.2'

    config.vm.network 'forwarded_port', guest: 5432, host: 5432

    config.berkshelf.enabled = true

    config.vm.provision 'chef_zero' do |chef|
        chef.nodes_path = 'nodes/'
        chef.cookbooks_path = 'cookbooks/'
        # chef.data_bags_path = 'databags/'

        chef.add_recipe 'postgresql::server_redhat'

        chef.json = {
            'postgresql' => {
                'dir' => '/var/lib/pgsql/data',
                'config' => {
                    'listen_addresses' => '0.0.0.0',
                    'data_directory' => '/var/lib/pgsql/data'
                },
                'pg_hba' => [
                    {type: 'host', db: 'all', user: 'postgres', addr: '0.0.0.0/0', method: 'trust'},
                    {type: 'local', db: 'all', user: 'vagrant', addr: nil, method: 'trust'}
                ]
            }
        }
    end
end
